services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "9500:9500"
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    environment:
      NODE_ENV: development
    command: npm run dev

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./api:/app"
    environment:
      PYTHONUNBUFFERED: 1
    command: uvicorn root:app --reload --host 0.0.0.0 --port 8000
