services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          action: rebuild
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - "9500:9500"
    environment:
      - DEV=1
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          action: rebuild
    volumes:
      - "./api:/app"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEV=1

  logs:
    image: gold66/lnav:latest
    volumes:
      - ./api/logs:/logs:ro
    stdin_open: true
    tty: true
    entrypoint: ["lnav", "/logs/API_log.log"]
    depends_on:
      - api
    profiles:
      - logs

volumes:
  db_data:
