services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - "9500:9500"
    environment:
      - DEV=1
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEV=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  logs:
    image: gold66/lnav:latest
    volumes:
      - ./api/logs:/logs:ro
    stdin_open: true
    tty: true
    entrypoint: ["lnav", "/logs/API_log.log"]
    depends_on:
      - api
    profiles:
      - logs

volumes:
  db_data:
