[project]
name = "AppTemplate-api"
version = "0.1.0"
description = "Project Description"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "sqlalchemy>=2.0.27",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.10",
]
